# Generated by Django 3.0.4 on 2020-05-07 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('amount_charged', models.FloatField()),
                ('remaining_cost', models.FloatField()),
                ('network', models.CharField(max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('stripe_receipt', models.CharField(max_length=100)),
                ('client', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
