# Generated by Django 3.0.4 on 2020-05-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='last4',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='network',
        ),
    ]
