# Generated by Django 3.0.4 on 2020-05-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0009_auto_20200504_1201'),
        ('payments', '0004_invoice_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.AddField(
            model_name='invoice',
            name='descrption',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='comms.order'),
        ),
    ]
