# Generated by Django 3.0.4 on 2020-05-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200507_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='descrption',
            new_name='description',
        ),
    ]
