# Generated by Django 3.0.4 on 2020-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
    ]
