# Generated by Django 3.0.4 on 2020-04-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='functionality',
            field=models.CharField(max_length=200, verbose_name='What would you like users to do on your website?'),
        ),
    ]
