# Generated by Django 3.0.4 on 2020-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_auto_20200419_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='business',
            new_name='business_type',
        ),
        migrations.AddField(
            model_name='order',
            name='business_name',
            field=models.CharField(default=1, max_length=50, verbose_name='What is the name of your business?'),
            preserve_default=False,
        ),
    ]
