# Generated by Django 3.0.4 on 2020-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0009_auto_20200504_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='website',
            field=models.CharField(choices=[('Landing page/Brochure website', 'Landing page/Brochure website'), ('Multipaged information website', 'Multipaged information website'), ('Ecommerce/ Webstore', 'Ecommerce/ Webstore'), ('Something Else', 'Something Else')], max_length=50, verbose_name='What kind of website would you like?*'),
        ),
    ]
