# Generated by Django 3.0.4 on 2020-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0011_auto_20200509_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='website',
            field=models.CharField(choices=[('Landing page/ Brochure website', 'Landing page/ Brochure website'), ('Multipaged information website', 'Multipaged information website'), ('Ecommerce/ Webstore', 'Ecommerce/ Webstore'), ('Something else', 'Something else')], max_length=50, verbose_name='What kind of website would you like?*'),
        ),
    ]
